title: Craig Dsouza
author: Craig Dsouza
description: Writing on technology with a focus on India
email: craigds022@gmail.com
baseurl: ""

# Collections
collections:
  reports:
    output: true
    permalink: /reports/:name
  tools:
    output: true
    permalink: /tools/:name

# Posts
permalink: /writings/:year/:month/:day/:title

# Build
markdown: kramdown
highlighter: rouge
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md", "Gemfile.lock"]

# Plugins
plugins:
  - jekyll-feed
